=== adiskovarik/pic_editor/pic_editor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="positions">
    <xs:restriction base="xs:string">
      <xs:pattern value="top|center|left|right|bottom"/>
    </xs:restriction>
  </xs:simpleType>
 <xs:simpleType name="colorhex">
        <xs:union memberTypes="xs:string">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="#[0-9a-fA-F]{6}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="layout">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="active_resolution">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="horizontal" type="xs:unsignedShort" />
                    <xs:element name="vertical" type="xs:unsignedShort" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="inner_frame">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="position">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="x" type="xs:unsignedShort" />
                          <xs:element name="y" type="xs:unsignedShort" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="size">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="width" type="xs:unsignedShort" />
                          <xs:element name="height" type="xs:unsignedShort" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="border">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="thickness" type="xs:unsignedByte" />
                          <xs:element name="color" type="colorhex" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="toolbars">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="toolbar">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="position">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="x" type="xs:unsignedShort" />
                                <xs:element name="y" type="xs:unsignedShort" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="size">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="width" type="xs:unsignedShort" />
                                <xs:element name="height" type="xs:unsignedShort" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="border">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="thickness" type="xs:unsignedByte" />
                                <xs:element name="color" type="colorhex" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="element_layout">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="element">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="position">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="x" type="xs:unsignedShort" />
                                            <xs:element name="y" type="xs:unsignedShort" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="size">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="width" type="xs:unsignedShort" />
                                            <xs:element name="height" type="xs:unsignedShort" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" name="border">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="thickness" type="xs:unsignedByte" />
                                            <xs:element name="color" type="colorhex" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" maxOccurs="unbounded" name="layer_id">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="hide_layer" type="xs:boolean" />
                                            <xs:element name="lock_layer" type="xs:boolean" />
                                          </xs:sequence>
                                          <xs:attribute name="id" type="xs:unsignedByte" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" name="color_slider">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="red" type="colorhex" />
                                            <xs:element name="green" type="colorhex" />
                                            <xs:element name="blue" type="colorhex" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" name="enable_filters" type="xs:boolean" />
                                      <xs:element minOccurs="0" name="look">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="shape">
                                              <xs:complexType>
                                                <xs:attribute name="shape" type="xs:string" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element name="corners">
                                              <xs:complexType>
                                                <xs:attribute name="radius" type="xs:unsignedByte" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element name="color">
                                              <xs:complexType>
                                                <xs:attribute name="color" type="colorhex" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element minOccurs="0" name="name">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="name_position">
                                                    <xs:complexType>
                                                      <xs:attribute name="position" type="xs:string" use="required" />
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element minOccurs="0" name="name_position">
                                              <xs:complexType>
                                                <xs:attribute name="position" type="xs:string" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" name="lock_ratio" type="xs:boolean" />
                                      <xs:element minOccurs="0" name="properties">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element minOccurs="0" name="default_font" type="xs:string" />
                                            <xs:element minOccurs="0" name="default_shape" type="xs:string" />
                                            <xs:element minOccurs="0" name="default_diameter" type="xs:unsignedByte" />
                                            <xs:element minOccurs="0" name="default_color" type="colorhex" />
                                            <xs:element minOccurs="0" name="default_size" type="xs:unsignedByte" />
                                            <xs:element minOccurs="0" name="default_gradient" type="xs:unsignedByte" />
                                            <xs:element minOccurs="0" name="default_opacity" type="xs:unsignedByte" />
                                            <xs:element minOccurs="0" maxOccurs="unbounded" name="style" type="xs:string" />
                                            <xs:element minOccurs="0" maxOccurs="unbounded" name="preset" type="xs:string" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="icon" type="xs:string" use="optional" />
                                    <xs:attribute name="type" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="key_mapping">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="keyboard">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="key">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="mapped_key" type="xs:string" />
                          <xs:element name="mapped_to" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="picture">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="file_extension" type="xs:string" />
              <xs:element name="file_default_size">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="width" type="xs:unsignedShort" />
                    <xs:element name="height" type="xs:unsignedShort" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="pic_default_color">
                <xs:complexType>
                  <xs:attribute name="color" type="colorhex" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="default_name" type="xs:string" use="required" />
            <xs:attribute name="defautl_extension" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adiskovarik/pic_editor/pic_editor.xml
<?xml version="1.0" encoding="utf-8"?>
<root
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="pic_editor.xsd">
  <layout>
    <active_resolution>
      <horizontal>1366</horizontal>
      <vertical>768</vertical>
    </active_resolution>
    <inner_frame>
      <position>
        <x>80</x>
        <y>80</y>
      </position>
      <size>
        <width>1020</width>
        <height>620</height>
      </size>
      <border>
        <thickness>1</thickness>
        <color>#000000</color>
      </border>
    </inner_frame>
    <toolbars>
      <toolbar name="Main Toolbar">
        <position>
          <x>0</x>
          <y>30</y>
        </position>
        <size>
          <width>1366</width>
          <height>50</height>
        </size>
        <border>
          <thickness>1</thickness>
          <color>#000000</color>
        </border>
        <element_layout>
          <element name="New" icon="new.png" type="button">
            <position>
              <x>10</x>
              <y>35</y>
            </position>
            <size>
              <width>70</width>
              <height>70</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="20"></corners>
              <color color ="#EEEEEE"></color>
              <name_position position = "bottom"></name_position>
            </look>
          </element>
          <element name="Paste" icon="paste.png" type="button">
            <position>
              <x>90</x>
              <y>35</y>
            </position>
            <size>
              <width>64</width>
              <height>64</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="20"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
          </element>
          <element name="Filters" icon="filters.png" type="button">
            <position>
              <x>170</x>
              <y>35</y>
            </position>
            <size>
              <width>64</width>
              <height>64</height>
            </size>
            <enable_filters>true</enable_filters>
            <look>
              <shape shape = "square"></shape>
              <corners radius="20"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <properties>
              <preset>vintage</preset>
              <preset>hdr</preset>
              <preset>blackandwhite</preset>
            </properties>
          </element>
          <element name="Transform" icon="transform.png" type="button">
            <position>
              <x>250</x>
              <y>35</y>
            </position>
            <size>
              <width>64</width>
              <height>64</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="20"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <lock_ratio>false</lock_ratio>
            <properties>
              <style>resize</style>
              <style>bend</style>
              <style>twist</style>
            </properties>
          </element>
        </element_layout>
      </toolbar>
      <toolbar name="Side Toolbar">
        <position>
          <x>0</x>
          <y>80</y>
        </position>
        <size>
          <width>30</width>
          <height>500</height>
        </size>
        <border>
          <thickness>1</thickness>
          <color>#000000</color>
        </border>
        <element_layout>
          <element name="Pen" icon="pen.png" type="button">
            <position>
              <x>5</x>
              <y>90</y>
            </position>
            <size>
              <width>20</width>
              <height>20</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="10"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <properties>
              <default_shape>circle</default_shape>
              <default_diameter>10</default_diameter>
              <default_color>#000000</default_color>
            </properties>
          </element>
          <element name="Brush" icon="brush.png" type="button">
            <position>
              <x>5</x>
              <y>120</y>
            </position>
            <size>
              <width>20</width>
              <height>20</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="10"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <properties>
              <default_shape>circle</default_shape>
              <default_diameter>10</default_diameter>
              <default_color>#000000</default_color>
              <default_gradient>0</default_gradient>
              <default_opacity>100</default_opacity>
            </properties>
          </element>
          <element name="Color Can" icon="can.png" type="button">
            <position>
              <x>5</x>
              <y>150</y>
            </position>
            <size>
              <width>20</width>
              <height>20</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="10"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <properties>
              <default_color>#000000</default_color>
            </properties>
          </element>
          <element name="Text" icon="text.png" type="button">
            <position>
              <x>5</x>
              <y>180</y>
            </position>
            <size>
              <width>20</width>
              <height>20</height>
            </size>
            <look>
              <shape shape = "square"></shape>
              <corners radius="10"></corners>
              <color color ="#EEEEEE"/>
              <name_position position = "bottom"></name_position>
            </look>
            <properties>
              <default_font>Arial</default_font>
              <default_color>#000000</default_color>
              <default_size>11</default_size>
            </properties>
          </element>
        </element_layout>
      </toolbar>
      <toolbar name ="Edit Toolbar">
        <position>
          <x>1100</x>
          <y>80</y>
        </position>
        <size>
          <width>360</width>
          <height>500</height>
        </size>
        <border>
          <thickness>1</thickness>
          <color>#000000</color>
        </border>
        <element_layout>
          <element name="Color Palette" type="colorpicker">
            <position>
              <x>1130</x>
             <y>80</y>
            </position>
            <size>
              <width>300</width>
              <height>200</height>
            </size>
            <color_slider>
              <red>#FF0000</red>
              <green>#00FF00</green>
              <blue>#0000FF</blue>
            </color_slider>
          </element>
          <element name="Layers" type="list">
            <position>
              <x>1130</x>
              <y>300</y>
            </position>
            <size>
              <width>300</width>
              <height>200</height>
            </size>
            <border>
              <thickness>1</thickness>
              <color>#000000</color>
            </border>
            <layer_id id="1">
              <hide_layer>false</hide_layer>
              <lock_layer>false</lock_layer>
            </layer_id>
            <layer_id id="2">
              <hide_layer>true</hide_layer>
              <lock_layer>false</lock_layer>
            </layer_id>
          </element>
        </element_layout>
      </toolbar>
    </toolbars>
  </layout>
  <key_mapping>
      <keyboard>
        <key>
          <mapped_key>+|ctrl+wheelup</mapped_key>
          <mapped_to>zoomin</mapped_to>
        </key>
        <key>
          <mapped_key>-|ctrl+wheeldown</mapped_key>
          <mapped_to>zoomout</mapped_to>
        </key>
        <key>
          <mapped_key>ctrl+rightclick</mapped_key>
          <mapped_to>crop</mapped_to>
        </key>
        <key>
          <mapped_key>ctrl+leftclick</mapped_key>
          <mapped_to>choose</mapped_to>
        </key>
      </keyboard>
    </key_mapping>
  <picture default_name="New picture" defautl_extension=".jpg">
    <file_extension>".jpg"</file_extension>
    <file_extension>".png"</file_extension>
    <file_extension>".bmp"</file_extension>
    <file_extension>".gif"</file_extension>
    <file_default_size>
      <width>800</width>
      <height>600</height>
    </file_default_size>
  <pic_default_color color ="#FFFFFF"></pic_default_color>
  </picture>
  </root>
